[package]
name = "docrafter-template"
readme = "../../README.md"
description = "Templates and report builders for docrafter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
docrafter-core.workspace = true
docrafter-office.workspace = true

[dev-dependencies]
docrafter-office.workspace = true

[lints]
workspace = true
